Spring:
  application:
    name : Dine-in-Order
  datasource:
    url : jdbc:mysql://localhost:3306/dine_in_db?createDatabaseIfNotExist=true
    username : root
    password : Veeresh@8296
  jpa:
    show-sql : true
    hibernate :
      ddl-auto : update




